### ISSUE TITLE
what's the use case

### ISSUE THREAD

**Issue by shaiss** [b-morgan/OctoPrint-FanSpeedMirror#1]
cool idea, but what's the use case?  I'm assuming it's to control auxiliary fans?

**Comment by b-morgan** [comment]
As stated in the README, a user-defined command is executed on the host when an M106 or an M107 is seen in the GCode. For M106, the decimal value of the S parameter (0-255) is appended to the user-defined command for M106.

I developed this plugin to control auxiliary fans connected to the Raspberry Pi that runs my 3D printer with OctoPrint. The scripts provided in [extras](https://github.com/b-morgan/OctoPrint-FanSpeedMirror/tree/master/extras) are the ones I use. The [Wiki](https://github.com/b-morgan/OctoPrint-FanSpeedMirror/wiki) provides additional documentation.

The scripts don't have to control auxiliary fans. They can do anything you want when the GCode M106 and M107 commands are executed.
